name: ASP.NET Core Deploy to FTP (Plesk)

on:
  push:
    branches:
      - main  # اگر شاخه‌ت master هست، همینجا تغییر بده

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -o publish_output

      - name: Remove specific wwwroot folders
        run: |
          
          if (Test-Path -Path .\publish_output\wwwroot\ckeditor) {
            Remove-Item -Path .\publish_output\wwwroot\ckeditor -Recurse -Force
          }
          if (Test-Path -Path .\publish_output\wwwroot\fontawesome) {
            Remove-Item -Path .\publish_output\wwwroot\fontawesome -Recurse -Force
          }

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: publish_output/
          server-dir: /httpdocs/
          exclude: |
            **/appsettings.json
            **/web.config
          dangerous-clean-slate: false
